retargeting:
  type: vector
  urdf_path: o6_left/linkerhand_o6_left.urdf

  # 只优化四个手指的 MCP
  target_joint_names: [
    "index_mcp_pitch",
    "middle_mcp_pitch",
    "ring_mcp_pitch",
    "pinky_mcp_pitch"
  ]

  target_origin_link_names: [
    "hand_base_link", "hand_base_link", "hand_base_link", "hand_base_link"
  ]
  target_task_link_names: [
    "index_tip", "middle_tip", "ring_tip", "pinky_tip"
  ]
  
  scaling_factor: 1.0

  # 四个手指的索引（跳过拇指）
  target_link_human_indices: [
    [0, 0, 0, 0],
    [1, 2, 3, 4]
  ]

  normal_delta: 0.005
  huber_delta: 0.02
  low_pass_alpha: 0.3
